# Generated by Django 5.1.1 on 2024-09-14 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_user_username_follow_post_like_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('followers', 'following')},
        ),
    ]
